# Generated by Django 2.2.12 on 2020-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200402_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
