# Generated by Django 2.2.12 on 2020-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200402_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rate',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_rate',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
