# Generated by Django 2.2.12 on 2020-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200402_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
